### ISSUE TITLE
Plugin Patching Exception

### ISSUE THREAD

**Issue by jiayev** [hakasapl/ParallaxGen#39]
When patching with this specific json, would 100% cause error. When i remove this json, the patching goes well.
![image](https://github.com/user-attachments/assets/4cc56186-098a-41ab-a077-887fe894a163)

[Beyond Skyrim - Bruma PBR - architecture.json](https://github.com/user-attachments/files/17547254/Beyond.Skyrim.-.Bruma.PBR.-.architecture.json)
[log.zip](https://github.com/user-attachments/files/17547303/log.zip)

**Comment by hakasapl** [comment]
Thanks! We will take a look

**Comment by jiayev** [comment]
Did some test,
```json
[
    {
        "texture": "bscyrodiil\\architecture\\farmhouse\\stonewall01",
        "emissive": false,
        "parallax": true,
        "subsurface": false,
        "multilayer": false,
        "subsurface_foliage": false,
        "specular_level": 0.04,
        "subsurface_color": [
            1,
            1,
            1
        ],
        "roughness_scale": 1,
        "subsurface_opacity": 1,
        "displacement_scale": 0.5,
        "smooth_angle": 70.0
    }
]
```

This is the exact one causing the error. The rest of the json is fine.

**Comment by hakasapl** [comment]
This is not only from PBR jsons it seems like, but I could be wrong. Here's some of my analysis:

I added additional trace logging and asked a user who was experiencing this to rerun with -vv.

In the log, these are the relevant messages:

```
[2024-11-13 03:35:11.722] [trace] [ParallaxGenMutagenWrapper] [GetMatchingTXSTObjs] Getting Matching TXST Objects for: (meshes\whbridgerevived\windhelmbridge2.nif, Windhelmbridge2:17, 0)
[2024-11-13 03:35:11.722] [error] Exception in thread patching NIF meshes\whbridgerevived\windhelmbridge2.nif: ParallaxGenMutagenWrapper.dll: 
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at ParallaxGenMutagenWrapper.PGMutagen.SetModelAltTexManage(Int32 AltTexHandle, Int32 TXSTHandle)
```

The ONLY trace log from the mutagen wrapper is a message from GetMatchingTXSTObjs about getting potential matches from this line in ParallaxGenPlugin.cpp:

```
const auto Matches = libGetMatchingTXSTObjs(NIFPath, Name3D, Index3DOld);
```

IF there was more than 0 matches, we needed to see other log messages confirming that, which we don't. This leads me to believe that the Matches vector has length 0, and therefore the loop proceeding it should not run.

But then we get this exception in `SetModelAltTexManage` which can be called from either `SetModelAltTex` (for which we would see a log message), or `CreateNewTXSTPatch` (for which we also would have seen a log message).

So we get an exception from a function that cannot possibly be invoked because
1. The matches vector should be empty
2. Even if it somehow wasn't empty, there should be other log messages if this function was triggered at all (from both ParallaxGenPlugin AND PGMutagen)

I am asking the user to run with multithreading disabled to see if the same crash occurs.

Updated code is in the [0.7test7](https://github.com/hakasapl/ParallaxGen/tree/0.7test7) branch
