### ISSUE TITLE
Plugin patching does not work with --upgrade-shaders

### ISSUE THREAD

**Issue by Sebastian-81** [hakasapl/ParallaxGen#48]
When using `--upgrade-shaders` the complex material maps are not found and warnings are issued during plugin patching

**Comment by hakasapl** [comment]
We should probably move the shader upgrade logic to its own new patcher since parallaxgenplugin will need to call it directly, and since it is in parallaxgen currently that will cause a circular include. For the logic itself:

1. Both the vanilla parallax shader and the CM shader need to be checked instead of just on in parallaxgenplugin
2. If both are available, the one with higher mod priority wins (same as parallaxgen.cpp logic)
3. If only parallax is available, upgrade shader
4. If only CM is available, continue as usual
5. If both are available and parallax wins, upgrade shader
